apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api
  namespace: greeting-apis
spec:
  replicas: 4
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
        - name: dotnet-api
          image: balenabdalla/dotnet-greeting-api:latest
          ports:
            - containerPort: 8082
