apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  namespace: greeting-apis
spec:
  replicas: 4
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: balenabdalla/go-greeting-api:latest
          ports:
            - containerPort: 8080
